#!/bin/bash
set -Eeuo pipefail
shopt -s inherit_errexit

setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
  else
    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
  fi
}

msg() {
  echo >&2 -e "${1-}"
}

usage() {
  cat << EOF
ignorectl - pacman.conf IgnorePkg manager

USAGE: $(basename "${BASH_SOURCE[0]}") <COMMAND> [ARGS]
    
COMMAND:
    (h)elp              - Show this help message
    (l)ist              - List all ignored packages defined in \
pacman.conf
    (a)dd <packages>    - Add packages to ignore list
    (r)emove <packages> - Remove packages from ignore list
EOF
  exit 1
}

list_pkgs() {
  grep -i '^ignorepkg' < /etc/pacman.conf | cut -d= -f2
}

list_ignored() {
  local pkgs=($(list_pkgs))
  printf "%s\n" "${pkgs[@]}"
}

add_pkgs() {
  local pkgs_add=($(printf "%s\n" "$@" | sort))
  local ignored_pkgs=($(list_pkgs))

  local merged=($(printf "%s\n" "${ignored_pkgs[@]}" \
    "${pkgs_add[@]}" | sort -u))

  sudo sed -i".old" "s/^IgnorePkg.*/IgnorePkg = ${merged[*]}/" /etc/pacman.conf

  # verification
  diff <(list_ignored) <(printf "%s\n" "${merged[@]}") \
    && {
      msg "${GREEN}Success adding packages!${NOFORMAT}"
      msg "${GREEN}+++${NOFORMAT}"

      local i=0
      for pkg in "${merged[@]}"; do
        if [[ $pkg = "${pkgs_add[$i]:-}" ]]; then
          echo -e "${GREEN}$pkg${NOFORMAT}"
          let i+=1
        else
          echo "$pkg"
        fi
      done
    }
}

remove_pkgs() {
  local ignored_pkgs=($(list_pkgs))
  local subbed=()
  local prints=()

  for pkg in ${ignored_pkgs[@]}; do
    if [[ $pkg = "${1:-}" ]]; then
      prints+=("${RED}${pkg}${NOFORMAT}")
      shift
    else
      subbed+=("$pkg")
      prints+=("$pkg")
    fi
  done

  if [[ $# -ne 0 ]]; then
    msg "\n${RED}ERROR:${NOFORMAT} Package '$1' not found!"
    msg "Operation cancelled...\n"
    exit 1
  fi

  sudo sed -i".old" "s/^IgnorePkg.*/IgnorePkg = ${subbed[*]}/" /etc/pacman.conf

  # verification
  diff <(list_ignored) <(printf "%s\n" "${subbed[@]}") \
    && {
      msg "${GREEN}Success removing packages!${NOFORMAT}"
      msg "${RED}---${NOFORMAT}"
      printf "%b\n" "${prints[@]}"
    }
}

parse_args() {
  if [[ $1 -eq 0 ]]; then
    msg "\n${RED}ERROR:${NOFORMAT} \
Args for ${GREEN}'$2'${NOFORMAT} not found!\n"
    usage
  else
    shift; shift
    # sort command args and store it to 'args' array
    IFS=$'\n' command eval \
      "args=($(printf "%s\n" "$@" | sort))"
  fi
}

main() {
  args=()

  case "${1:-}" in
    h|help) usage ;;
    l|list) list_ignored ;;
    a|add)
      shift
      parse_args "$#" "add" "${@}"
      add_pkgs "${args[@]}"
      ;;
    r|remove)
      shift
      parse_args "$#" "remove" "${@}"
      remove_pkgs "${args[@]}"
      ;;
    *)
      msg "\n${RED}ERROR:${NOFORMAT} Command \
${GREEN}'${1:-}'${NOFORMAT} not found!\n"
      usage
      ;;
  esac
}

setup_colors
main "${@}"
